import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Medicine, MedicineDocument } from '../schemas/medicine.schema';

@Injectable()
export class MedicinesSeeder {
  constructor(
    @InjectModel(Medicine.name) private medicineModel: Model<MedicineDocument>,
  ) {}

  async seedMedicines() {
    const existingCount = await this.medicineModel.countDocuments();
    if (existingCount > 0) {
      console.log('Medicines already seeded');
      return;
    }

    const sampleMedicines = [
      {
        name: 'Paracetamol 500mg',
        genericName: 'Acetaminophen',
        manufacturer: 'ABC Pharmaceuticals',
        description: 'Pain reliever and fever reducer. Effective for headaches, muscle aches, and minor pain.',
        category: 'Pain Relief',
        price: 25.00,
        mrp: 30.00,
        stock: 100,
        unit: 'tablets',
        packSize: '10 tablets',
        dosage: '500mg',
        form: 'tablet',
        activeIngredients: ['Acetaminophen 500mg'],
        images: ['/images/medicines/paracetamol.jpg'],
        prescriptionRequired: false,
        tags: ['pain relief', 'fever', 'headache'],
        rating: 4.5,
        reviewCount: 120,
        discount: 17,
        isFeatured: true,
      },
      {
        name: 'Amoxicillin 250mg',
        genericName: 'Amoxicillin',
        manufacturer: 'XYZ Pharma',
        description: 'Antibiotic used to treat bacterial infections including pneumonia, bronchitis, and ear infections.',
        category: 'Antibiotics',
        price: 85.00,
        mrp: 100.00,
        stock: 50,
        unit: 'capsules',
        packSize: '10 capsules',
        dosage: '250mg',
        form: 'capsule',
        activeIngredients: ['Amoxicillin 250mg'],
        images: ['/images/medicines/amoxicillin.jpg'],
        prescriptionRequired: true,
        tags: ['antibiotic', 'infection', 'bacterial'],
        rating: 4.2,
        reviewCount: 85,
        discount: 15,
        isFeatured: false,
      },
      {
        name: 'Cetirizine 10mg',
        genericName: 'Cetirizine Hydrochloride',
        manufacturer: 'HealthCare Ltd',
        description: 'Antihistamine used to treat allergy symptoms such as runny nose, sneezing, and itching.',
        category: 'Allergy & Cold',
        price: 45.00,
        mrp: 50.00,
        stock: 75,
        unit: 'tablets',
        packSize: '10 tablets',
        dosage: '10mg',
        form: 'tablet',
        activeIngredients: ['Cetirizine Hydrochloride 10mg'],
        images: ['/images/medicines/cetirizine.jpg'],
        prescriptionRequired: false,
        tags: ['allergy', 'antihistamine', 'cold'],
        rating: 4.3,
        reviewCount: 95,
        discount: 10,
        isFeatured: true,
      },
      {
        name: 'Metformin 500mg',
        genericName: 'Metformin Hydrochloride',
        manufacturer: 'Diabetes Care Inc',
        description: 'Medication used to treat type 2 diabetes by controlling blood sugar levels.',
        category: 'Diabetes',
        price: 120.00,
        mrp: 140.00,
        stock: 60,
        unit: 'tablets',
        packSize: '30 tablets',
        dosage: '500mg',
        form: 'tablet',
        activeIngredients: ['Metformin Hydrochloride 500mg'],
        images: ['/images/medicines/metformin.jpg'],
        prescriptionRequired: true,
        tags: ['diabetes', 'blood sugar', 'type 2'],
        rating: 4.4,
        reviewCount: 150,
        discount: 14,
        isFeatured: true,
      },
      {
        name: 'Omeprazole 20mg',
        genericName: 'Omeprazole',
        manufacturer: 'Gastro Pharmaceuticals',
        description: 'Proton pump inhibitor used to treat acid reflux, GERD, and stomach ulcers.',
        category: 'Digestive Health',
        price: 95.00,
        mrp: 110.00,
        stock: 40,
        unit: 'capsules',
        packSize: '14 capsules',
        dosage: '20mg',
        form: 'capsule',
        activeIngredients: ['Omeprazole 20mg'],
        images: ['/images/medicines/omeprazole.jpg'],
        prescriptionRequired: true,
        tags: ['acid reflux', 'gerd', 'stomach'],
        rating: 4.1,
        reviewCount: 78,
        discount: 14,
        isFeatured: false,
      },
      {
        name: 'Vitamin D3 1000 IU',
        genericName: 'Cholecalciferol',
        manufacturer: 'Wellness Supplements',
        description: 'Essential vitamin for bone health, immune function, and calcium absorption.',
        category: 'Vitamins & Supplements',
        price: 180.00,
        mrp: 200.00,
        stock: 90,
        unit: 'tablets',
        packSize: '30 tablets',
        dosage: '1000 IU',
        form: 'tablet',
        activeIngredients: ['Cholecalciferol 1000 IU'],
        images: ['/images/medicines/vitamin-d3.jpg'],
        prescriptionRequired: false,
        tags: ['vitamin', 'bone health', 'immunity'],
        rating: 4.6,
        reviewCount: 200,
        discount: 10,
        isFeatured: true,
      },
      {
        name: 'Aspirin 75mg',
        genericName: 'Acetylsalicylic Acid',
        manufacturer: 'Cardio Care',
        description: 'Low-dose aspirin for cardiovascular protection and blood clot prevention.',
        category: 'Cardiovascular',
        price: 65.00,
        mrp: 75.00,
        stock: 80,
        unit: 'tablets',
        packSize: '30 tablets',
        dosage: '75mg',
        form: 'tablet',
        activeIngredients: ['Acetylsalicylic Acid 75mg'],
        images: ['/images/medicines/aspirin.jpg'],
        prescriptionRequired: true,
        tags: ['cardio', 'blood thinner', 'heart'],
        rating: 4.2,
        reviewCount: 110,
        discount: 13,
        isFeatured: false,
      },
      {
        name: 'Ibuprofen 400mg',
        genericName: 'Ibuprofen',
        manufacturer: 'Pain Relief Co',
        description: 'Nonsteroidal anti-inflammatory drug (NSAID) for pain, inflammation, and fever.',
        category: 'Pain Relief',
        price: 55.00,
        mrp: 65.00,
        stock: 70,
        unit: 'tablets',
        packSize: '10 tablets',
        dosage: '400mg',
        form: 'tablet',
        activeIngredients: ['Ibuprofen 400mg'],
        images: ['/images/medicines/ibuprofen.jpg'],
        prescriptionRequired: false,
        tags: ['pain relief', 'inflammation', 'fever'],
        rating: 4.3,
        reviewCount: 130,
        discount: 15,
        isFeatured: true,
      },
    ];

    try {
      await this.medicineModel.insertMany(sampleMedicines);
      console.log('Sample medicines seeded successfully');
    } catch (error) {
      console.error('Error seeding medicines:', error);
    }
  }
}
