// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPn-tCDgRtJAq4C04tukdeQbKxkiyTiJE',
    appId: '1:64313762655:web:c2586c91b807bac4a00cea',
    messagingSenderId: '64313762655',
    projectId: 'telemedicine-7a63c',
    authDomain: 'telemedicine-7a63c.firebaseapp.com',
    storageBucket: 'telemedicine-7a63c.firebasestorage.app',
    measurementId: 'G-KFE5RRNRXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9gdFmeYJRCIDbUrIl_XXkRReZi0Qru5s',
    appId: '1:64313762655:android:2e9556704d0cbb1ba00cea',
    messagingSenderId: '64313762655',
    projectId: 'telemedicine-7a63c',
    storageBucket: 'telemedicine-7a63c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAPf-BkD9Gco_7c242mR-h_miuUuefxK8',
    appId: '1:64313762655:ios:a33223167f3b90e8a00cea',
    messagingSenderId: '64313762655',
    projectId: 'telemedicine-7a63c',
    storageBucket: 'telemedicine-7a63c.firebasestorage.app',
    iosBundleId: 'com.example.telemedicineV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAPf-BkD9Gco_7c242mR-h_miuUuefxK8',
    appId: '1:64313762655:ios:a33223167f3b90e8a00cea',
    messagingSenderId: '64313762655',
    projectId: 'telemedicine-7a63c',
    storageBucket: 'telemedicine-7a63c.firebasestorage.app',
    iosBundleId: 'com.example.telemedicineV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPn-tCDgRtJAq4C04tukdeQbKxkiyTiJE',
    appId: '1:64313762655:web:ab8d2ba748b50625a00cea',
    messagingSenderId: '64313762655',
    projectId: 'telemedicine-7a63c',
    authDomain: 'telemedicine-7a63c.firebaseapp.com',
    storageBucket: 'telemedicine-7a63c.firebasestorage.app',
    measurementId: 'G-N0P6XEYCDM',
  );
}
